kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurito
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apicurito
subjects:
  - kind: ServiceAccount
    name: apicurito
    namespace: apicurito
